# Generated by Django 3.2.5 on 2022-02-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorpCodeModel',
            fields=[
                ('corp_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('corp_name', models.CharField(max_length=40, null=True)),
                ('stock_code', models.CharField(max_length=8, null=True)),
                ('add_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DartListModel',
            fields=[
                ('rcept_no', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('corp_code', models.CharField(max_length=10)),
                ('corp_name', models.CharField(max_length=40, null=True)),
                ('stock_code', models.CharField(max_length=8, null=True)),
                ('corp_cls', models.CharField(max_length=3, null=True)),
                ('report_name', models.CharField(max_length=40, null=True)),
                ('fir_nm', models.CharField(max_length=20, null=True)),
                ('rcept_dt', models.DateTimeField()),
            ],
        ),
    ]
