# Generated by Django 3.2.5 on 2022-02-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disclosure', '0002_dartlistmodel_rm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dartlistmodel',
            name='corp_cls',
            field=models.TextField(null=True),
        ),
    ]
