# Generated by Django 3.2.5 on 2022-03-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disclosure', '0003_alter_dartlistmodel_corp_cls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dartlistmodel',
            name='corp_name',
            field=models.CharField(db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dartlistmodel',
            name='rcept_dt',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dartlistmodel',
            name='stock_code',
            field=models.CharField(db_index=True, max_length=8, null=True),
        ),
    ]
